### ISSUE TITLE
Request - Adding flair-script to the template

### ISSUE THREAD

**Issue by XcomPsyCHo** [stupidpupil/voicepack_template#3]
Less of an issue, more of an request. 

I tried to add flair-script to the template, but failed. I guess I need to edit ProjectTemplate.x2proj for it to automatically appear, but I am not sure how that works. 

File is in .uc.txt because .uc are not supported

Some more info about flairs at https://www.reddit.com/r/xcom2mods/comments/4l3qvs/psa_for_voicepack_creators_add_flair_to_packs/

[UISL_Mod.uc.txt](https://github.com/stupidpupil/voicepack_template/files/6443379/UISL_Mod.uc.txt)

**Comment by stupidpupil** [comment]
This is to add icons/images next to Voice names, is that right?

**Comment by Iridar** [comment]
Script isn't required for this, you can add html images right in localization.

**Comment by Iridar** [comment]
For example:

```
[Shins_Templar_RatTail_F X2BodyPartTemplate]
DisplayName="<img src='img:///IRI_Anthro_UI.AnthroIcon' width='26' height='26' vspace='-4'>Rat Tail"
```
It's highly preferable to using a UIScreenListener. Every UISL ever so slightly reduces game's performance, and in general it's a very roundabout way of doing things.

**Comment by stupidpupil** [comment]
With that in mind, I can't see a good reason not to close this as wontfix, unless I've missed something?

**Comment by XcomPsyCHo** [comment]
Nope, Iridar's example will do the trick. Thanks.

**Comment by stupidpupil** [comment]
Thanks both. (I'll try to add Iridar's example to this template's documentation, but I've been away from the whole thing for a while.)
